// Subtítulos descriptivos por capítulo — adición editorial.
// Los capítulos bíblicos no tienen títulos canónicos (Stephen Langton los
// dividió en 1227). Estos son resúmenes pastorales para ayudar a ubicarse.

export const TITULOS_CAPITULOS: Record<string, string[]> = {
  // ─────────── AT · Pentateuco ───────────
  GEN: [
    "La Creación",
    "El Edén y la primera pareja",
    "La Caída · primer evangelio",
    "Caín y Abel",
    "Descendencia de Adán a Noé",
    "Maldad y anuncio del diluvio",
    "El arca y la entrada al diluvio",
    "El fin del diluvio",
    "Pacto del arcoíris",
    "Las naciones tras Noé",
    "Babel y los descendientes de Sem",
    "Llamado de Abram",
    "Abram y Lot se separan",
    "Abram rescata a Lot",
    "Pacto con Abram",
    "Agar e Ismael",
    "Pacto de la circuncisión",
    "Tres visitantes en Mamre",
    "Destrucción de Sodoma",
    "Abraham, Sara y Abimelec",
    "Nacimiento de Isaac",
    "Sacrificio en Moriah",
    "Muerte y entierro de Sara",
    "Esposa para Isaac · Rebeca",
    "Muerte de Abraham · Jacob y Esaú",
    "Isaac en Gerar",
    "Jacob recibe la bendición",
    "Jacob huye a Harán",
    "Jacob, Lía y Raquel",
    "Los hijos de Jacob",
    "Jacob regresa con su familia",
    "Lucha en Peniel",
    "Reencuentro con Esaú",
    "Dina y los siquemitas",
    "Jacob vuelve a Bet-el",
    "Genealogía de Esaú",
    "Los sueños de José",
    "Judá y Tamar",
    "José en casa de Potifar",
    "José y los sueños en la cárcel",
    "El sueño del faraón",
    "Los hermanos de José en Egipto",
    "Segundo viaje a Egipto",
    "La copa de José",
    "José se da a conocer",
    "Israel baja a Egipto",
    "Israel se asienta en Gosén",
    "Jacob bendice a los hijos de José",
    "Bendiciones a las doce tribus",
    "Muerte de Jacob y José",
  ],
  EXO: [
    "Israel oprimido en Egipto",
    "Nacimiento de Moisés",
    "La zarza ardiente",
    "Moisés vuelve a Egipto",
    "Primer encuentro con el faraón",
    "Dios confirma su pacto",
    "Vara y serpiente · plaga 1",
    "Plagas 2, 3 y 4",
    "Plagas 5, 6 y 7",
    "Plagas 8 y 9",
    "Anuncio de la última plaga",
    "La Pascua y la décima plaga",
    "Primogénitos y panes sin levadura",
    "Cruce del mar Rojo",
    "Cántico de Moisés · agua amarga",
    "Maná y codornices",
    "Agua de la roca · Amalec",
    "Jetro aconseja a Moisés",
    "Israel llega al Sinaí",
    "Los Diez Mandamientos",
    "Leyes sobre el prójimo",
    "Más leyes civiles",
    "Justicia y fiestas anuales",
    "Confirmación del pacto",
    "Ofrenda y arca del pacto",
    "El Tabernáculo",
    "Altar y atrio del Tabernáculo",
    "Vestiduras sacerdotales",
    "Consagración de los sacerdotes",
    "Altar del incienso · expiación",
    "Bezaleel y Aholiab · día de reposo",
    "El becerro de oro",
    "Tabernáculo de reunión",
    "Nuevas tablas de la Ley",
    "Día de reposo · ofrenda voluntaria",
    "Construcción del Tabernáculo",
    "Arca, mesa y candelero",
    "Altar, atrio y materiales",
    "Vestiduras y conclusión",
    "Erección del Tabernáculo · gloria",
  ],
  LEV: [
    "Holocausto",
    "Ofrenda vegetal",
    "Ofrenda de paz",
    "Ofrenda por el pecado",
    "Ofrenda por la culpa",
    "Más leyes de ofrendas",
    "Ofrendas del sacerdote",
    "Consagración de Aarón",
    "Inauguración del sacerdocio",
    "Nadab y Abiú · fuego extraño",
    "Animales puros e impuros",
    "Purificación tras el parto",
    "Lepra · diagnóstico",
    "Purificación del leproso",
    "Flujos corporales",
    "Día de Expiación",
    "La sangre y el lugar del sacrificio",
    "Relaciones prohibidas",
    "Santidad práctica",
    "Penas para pecados graves",
    "Santidad de los sacerdotes",
    "Reglas sobre las ofrendas",
    "Fiestas anuales del Señor",
    "Aceite, panes y maldicidores",
    "Año sabático y jubileo",
    "Bendiciones y maldiciones",
    "Votos y consagraciones",
  ],
  NUM: [
    "Primer censo de Israel",
    "Orden del campamento",
    "Los levitas y los primogénitos",
    "Servicio de los levitas",
    "Pruebas de pureza y celos",
    "Nazareato y bendición sacerdotal",
    "Ofrendas de los príncipes",
    "Consagración de los levitas",
    "Segunda Pascua · nube y fuego",
    "Trompetas · partida del Sinaí",
    "Quejas, codornices y los setenta",
    "María y Aarón murmuran",
    "Los doce espías",
    "Rebelión y juicio en Cades",
    "Más leyes · sábado violado",
    "Rebelión de Coré",
    "La vara de Aarón florece",
    "Deberes y diezmos levíticos",
    "La vaca alazana",
    "Aguas de Meriba · muerte de Aarón",
    "Serpiente de bronce · victorias",
    "Balaam y la asna",
    "Bendiciones de Balaam (1-2)",
    "Bendiciones de Balaam (3-4)",
    "Idolatría con Baal-peor",
    "Segundo censo",
    "Hijas de Zelofehad · sucesor",
    "Ofrendas diarias y festivas",
    "Más fiestas anuales",
    "Reglas sobre los votos",
    "Guerra contra Madián",
    "Tribus al oriente del Jordán",
    "Itinerario del éxodo",
    "Límites de Canaán",
    "Ciudades de los levitas y refugio",
    "Herencia de las hijas",
  ],
  DEU: [
    "Repaso desde Horeb",
    "Camino hacia Canaán",
    "Conquistas al oriente del Jordán",
    "Llamado a obedecer la Ley",
    "Los Diez Mandamientos repetidos",
    "El Shemá · ama al Señor",
    "Pueblo escogido y santo",
    "No olvides a Jehová",
    "El becerro de oro recordado",
    "Nuevas tablas · circuncidad el corazón",
    "Lealtad al único Dios",
    "Lugar central de adoración",
    "Falsos profetas",
    "Animales puros · diezmo",
    "Año de remisión · esclavos",
    "Tres fiestas · jueces",
    "Reyes y profetas",
    "El profeta como Moisés",
    "Ciudades de refugio",
    "Reglas para la guerra",
    "Leyes diversas",
    "Más leyes prácticas",
    "Quién entra a la congregación",
    "Justicia y compasión",
    "Pena, levirato y honestidad",
    "Primicias y diezmos",
    "Bendiciones de Gerizim, maldiciones de Ebal",
    "Bendiciones y maldiciones del pacto",
    "Renovación del pacto",
    "Promesa de restauración",
    "Despedida de Moisés",
    "Cántico de Moisés",
    "Bendiciones a las tribus",
    "Muerte de Moisés",
  ],

  // ─────────── AT · Históricos ───────────
  JOS: [
    "Llamado a Josué",
    "Rahab y los espías",
    "Cruce del Jordán",
    "Las doce piedras",
    "Circuncisión y Pascua en Gilgal",
    "Caída de Jericó",
    "Acán y la derrota en Hai",
    "Toma de Hai",
    "Engaño de los gabaonitas",
    "El sol detenido · victoria del sur",
    "Conquista del norte",
    "Lista de reyes vencidos",
    "Tierra por repartir",
    "Caleb pide Hebrón",
    "Heredad de Judá",
    "Heredad de Efraín y Manasés",
    "Más herencia para Manasés",
    "Restantes herencias en Silo",
    "Heredad de Benjamín y otros",
    "Ciudades de refugio",
    "Ciudades levíticas",
    "Tribus orientales vuelven",
    "Despedida de Josué",
    "Renovación del pacto · Siquem",
  ],
  JDG: [
    "Conquistas inacabadas",
    "El ángel en Boquim",
    "Otoniel, Aod y Samgar",
    "Débora y Barac",
    "Cántico de Débora",
    "Llamado de Gedeón",
    "Gedeón y los 300",
    "Gedeón persigue a Madián",
    "Abimelec, rey de Siquem",
    "Tola y Jair · opresión amonita",
    "Jefté",
    "Jefté y los efrainitas · jueces menores",
    "Anuncio del nacimiento de Sansón",
    "Sansón y la mujer de Timnat",
    "Hazañas con la quijada de asno",
    "Sansón y Dalila",
    "Idolatría de Micaía",
    "Los danitas y el ídolo",
    "La violación en Gabaa",
    "Guerra contra Benjamín",
    "Mujeres para Benjamín",
  ],
  RUT: [
    "Noemí y sus nueras en Moab",
    "Rut espiga en el campo de Booz",
    "Rut a los pies de Booz",
    "Booz redime a Rut · genealogía de David",
  ],
  "1SA": [
    "Nacimiento de Samuel",
    "Cántico de Ana · pecados de los hijos de Elí",
    "Llamado de Samuel",
    "El arca capturada",
    "El arca entre los filisteos",
    "Devolución del arca",
    "Victoria en Eben-ezer",
    "Israel pide un rey",
    "Saúl conoce a Samuel",
    "Saúl ungido rey",
    "Saúl libera a Jabes",
    "Despedida de Samuel",
    "Saúl ofrece sacrificio precipitado",
    "Jonatán y la victoria sobre los filisteos",
    "Saúl desobedece con Amalec",
    "Unción de David",
    "David y Goliat",
    "Jonatán ama a David · celos de Saúl",
    "Saúl persigue a David",
    "Jonatán y David se despiden",
    "David huye a Nob · panes de la proposición",
    "David en la cueva de Adulam",
    "David salva a Keila",
    "David perdona a Saúl en En-gadi",
    "Muerte de Samuel · Nabal y Abigail",
    "David perdona a Saúl por segunda vez",
    "David entre los filisteos",
    "Saúl y la adivina de Endor",
    "David despedido por los filisteos",
    "David recupera a su gente en Siclag",
    "Muerte de Saúl y sus hijos",
  ],
  "2SA": [
    "David lamenta a Saúl",
    "David ungido sobre Judá · guerra con Is-boset",
    "Muerte de Abner",
    "Muerte de Is-boset",
    "David rey sobre todo Israel · toma Jerusalén",
    "El arca traída a Jerusalén",
    "El pacto davídico",
    "Victorias de David",
    "David y Mefiboset",
    "Guerra con los amonitas",
    "David, Betsabé y Urías",
    "Natán confronta a David",
    "Amnón y Tamar · venganza de Absalón",
    "Absalón regresa",
    "Absalón se rebela",
    "David huye · Simei lo maldice",
    "Consejo de Ahitofel y Husai",
    "Muerte de Absalón",
    "David regresa a Jerusalén",
    "Rebelión de Seba",
    "Hambre · venganza gabaonita",
    "Cántico de victoria de David",
    "Últimas palabras y valientes de David",
    "Censo y plaga · era de Arauna",
  ],
  "1KI": [
    "Adonías intenta usurpar · Salomón ungido",
    "Últimas instrucciones de David",
    "Salomón pide sabiduría",
    "Funcionarios y prosperidad",
    "Preparativos para el Templo",
    "Construcción del Templo",
    "Palacio y muebles del Templo",
    "Dedicación del Templo",
    "Pacto con Salomón · obras civiles",
    "Reina de Sabá visita a Salomón",
    "Apostasía y muerte de Salomón",
    "División del reino",
    "Profeta de Judá y el profeta viejo",
    "Muerte del hijo de Jeroboam",
    "Reyes Asa de Judá y Nadab de Israel",
    "Más reyes de Israel · Acab",
    "Elías y la sequía · viuda de Sarepta",
    "Elías en el monte Carmelo",
    "Elías huye al Horeb",
    "Acab vence a Ben-adad",
    "Viña de Nabot",
    "Profecía contra Acab · muerte en Ramot",
  ],
  "2KI": [
    "Elías y los mensajeros de Ocozías",
    "Elías arrebatado · Eliseo lo sucede",
    "Eliseo y Moab",
    "Milagros de Eliseo",
    "Naamán sanado de lepra",
    "Hacha que flota · arameos cegados",
    "Sitio y hambre en Samaria",
    "Eliseo y Hazael · reyes de Judá",
    "Jehú unge rey · cae Jezabel",
    "Jehú extermina a los baalistas",
    "Atalía y el rescate de Joás",
    "Joás repara el Templo",
    "Reyes de Israel · muerte de Eliseo",
    "Jeroboam II · Azarías de Judá",
    "Más reyes de Israel y Judá",
    "Acaz y la alianza con Asiria",
    "Caída de Israel · Asiria deporta",
    "Reforma de Ezequías",
    "Invasión asiria · Ezequías ora",
    "Liberación milagrosa de Jerusalén",
    "Enfermedad y orgullo de Ezequías",
    "Manasés y Amón",
    "Reforma de Josías",
    "Pascua de Josías · muerte en Meguido",
    "Caída de Jerusalén",
  ],
  "1CH": [
    "Adán a Abraham",
    "Hijos de Israel",
    "Hijos de David",
    "Genealogía de Judá",
    "Tribus orientales",
    "Genealogía de Leví",
    "Otras tribus",
    "Genealogía de Benjamín y Saúl",
    "Lista de los que volvieron",
    "Muerte de Saúl",
    "David toma Jerusalén · valientes",
    "Más valientes vienen a David",
    "Traslado del arca · Uza",
    "David y Hiram · victorias filisteas",
    "Arca llevada a Jerusalén",
    "Asaf · cánticos de alabanza",
    "El pacto davídico (Crónicas)",
    "Victorias militares",
    "Guerra con amonitas y arameos",
    "Más victorias · Goliateos",
    "Censo y peste",
    "David prepara el Templo",
    "Organización de los levitas",
    "Turnos de los sacerdotes",
    "Cantores del Templo",
    "Porteros, tesoreros, jueces",
    "Comandantes militares",
    "David exhorta sobre el Templo",
    "Últimas oraciones y muerte de David",
  ],
  "2CH": [
    "Salomón pide sabiduría",
    "Preparativos para el Templo",
    "Salomón construye el Templo",
    "Muebles del Templo",
    "Traslado del arca",
    "Oración de dedicación",
    "Dios responde a Salomón",
    "Más obras de Salomón",
    "Reina de Sabá · muerte de Salomón",
    "División del reino",
    "Reinado de Roboam",
    "Sisac invade Judá",
    "Abías derrota a Jeroboam",
    "Reformas de Asa",
    "Asa y el profeta Azarías",
    "Asa se apoya en Siria",
    "Josafat fortalece a Judá",
    "Josafat y Acab",
    "Reformas judiciales de Josafat",
    "Cántico de victoria de Josafat",
    "Joram y Ocozías",
    "Atalía · rescate de Joás",
    "Joás y Joiada reparan el Templo",
    "Apostasía de Joás",
    "Amasías",
    "Uzías · su lepra",
    "Reinado de Jotam",
    "Acaz y la idolatría",
    "Ezequías limpia el Templo",
    "Gran Pascua de Ezequías",
    "Reorganización del culto",
    "Senaquerib y la oración de Ezequías",
    "Manasés humillado · Amón",
    "Josías y el libro de la Ley",
    "Pascua de Josías",
    "Caída final · decreto de Ciro",
  ],
  EZR: [
    "Decreto de Ciro · primer regreso",
    "Lista de los repatriados",
    "Reconstrucción del altar y cimientos",
    "Oposición a la obra",
    "Hageo y Zacarías animan",
    "Decreto de Darío · Templo terminado",
    "Esdras regresa",
    "Lista del segundo grupo",
    "Esdras ora por los matrimonios mixtos",
    "Reforma de los matrimonios",
  ],
  NEH: [
    "Nehemías oye y ora",
    "Nehemías viaja a Jerusalén",
    "Lista de los que reedifican el muro",
    "Oposición y guardia con espada",
    "Nehemías corrige la usura",
    "Conspiración contra Nehemías · muro terminado",
    "Censo de los repatriados",
    "Esdras lee la Ley",
    "Confesión nacional",
    "Lista de los que sellan el pacto",
    "Habitantes de Jerusalén y otras ciudades",
    "Lista de sacerdotes y levitas",
    "Reformas finales de Nehemías",
  ],
  EST: [
    "Vasti rechazada",
    "Ester elegida reina · Mardoqueo descubre la trama",
    "Amán planea exterminar a los judíos",
    "Mardoqueo ruega a Ester intervenir",
    "Ester invita al rey y a Amán",
    "Honra para Mardoqueo",
    "Caída de Amán",
    "Decreto a favor de los judíos",
    "Victoria · institución de Purim",
    "Grandeza de Mardoqueo",
  ],

  // ─────────── AT · Poéticos ───────────
  JOB: [
    "Job, justo · primera prueba",
    "Segunda prueba · los tres amigos",
    "Job maldice el día de su nacimiento",
    "Primer discurso de Elifaz",
    "Continúa Elifaz",
    "Respuesta de Job a Elifaz",
    "Job clama a Dios",
    "Primer discurso de Bildad",
    "Job responde",
    "Job sigue clamando",
    "Primer discurso de Zofar",
    "Job defiende su sabiduría",
    "Job apela a Dios",
    "Brevedad de la vida humana",
    "Segundo discurso de Elifaz",
    "Job responde a Elifaz",
    "Job clama por un mediador",
    "Segundo discurso de Bildad",
    "«Yo sé que mi Redentor vive»",
    "Segundo discurso de Zofar",
    "Job sobre la prosperidad de los impíos",
    "Tercer discurso de Elifaz",
    "Job anhela encontrar a Dios",
    "Job describe la injusticia",
    "Tercer discurso de Bildad",
    "Job sobre el poder de Dios",
    "Job mantiene su integridad",
    "Himno a la sabiduría",
    "Job recuerda sus días de honra",
    "Job lamenta su situación actual",
    "El juramento de inocencia de Job",
    "Primer discurso de Eliú",
    "Eliú: Dios habla en sueños y dolor",
    "Eliú defiende la justicia de Dios",
    "Eliú: Dios escucha al humilde",
    "Eliú: la majestad de Dios",
    "Dios desde el torbellino · creación",
    "Dios habla de los animales salvajes",
    "Dios responde · Behemot",
    "Dios responde · Behemot (continúa)",
    "Dios: Leviatán",
    "Job se arrepiente · restauración",
  ],
  PSA: [
    "Los dos caminos",
    "El Rey mesiánico",
    "Oración matutina · perseguido",
    "Confianza en Dios al acostarse",
    "Súplica al amanecer",
    "Súplica en tiempo de aflicción",
    "Confianza en Dios justo Juez",
    "¡Cuán glorioso es tu nombre!",
    "Gracias por la justicia divina",
    "¿Por qué te alejas, Señor?",
    "Confianza en el Señor",
    "Oración contra la mentira",
    "¿Hasta cuándo, Señor?",
    "El necio dice: «No hay Dios»",
    "¿Quién habitará en tu santuario?",
    "Heredad eterna en el Señor",
    "Apelo al Justo",
    "Cántico de victoria de David",
    "Los cielos cuentan la gloria",
    "Oración por el rey antes de la batalla",
    "Gracias por la victoria",
    "Salmo mesiánico de la cruz",
    "El Señor es mi pastor",
    "El Rey de gloria entra",
    "Enséñame tus caminos",
    "Examen del corazón",
    "El Señor es mi luz",
    "Oye mi súplica, Señor",
    "Tributad al Señor gloria",
    "Cántico tras la sanidad",
    "En tus manos encomiendo mi espíritu",
    "Bienaventuranza del perdonado",
    "Cántico nuevo de alabanza",
    "Bendeciré al Señor en todo tiempo",
    "Pleitea contra mis adversarios",
    "Maldad humana y misericordia divina",
    "No te impacientes a causa de los malignos",
    "Oración del afligido",
    "Brevedad de la vida humana",
    "Esperé pacientemente al Señor",
    "Bienaventurado el que piensa en el pobre",
    "¿Por qué te abates, alma mía?",
    "Anhelo del Templo · «como el ciervo»",
    "Súplica por la causa propia",
    "Maravillas de antaño",
    "Cántico nupcial mesiánico",
    "Dios es nuestro refugio · «Estad quietos»",
    "Pueblos, batid las manos",
    "Hermoso monte Sión",
    "La vanidad de las riquezas",
    "Dios Juez · culto verdadero",
    "Miserere · arrepentimiento de David",
    "El necio confía en su maldad",
    "El necio (repetición)",
    "Sálvame por tu nombre",
    "Quien me traiciona fue mi amigo",
    "Confianza en Dios cuando el enemigo me observa",
    "Misericordia y verdad",
    "¿Habláis verdaderamente, jueces?",
    "Líbrame de mis enemigos",
    "Restáuranos, oh Dios",
    "Oye mi clamor, Señor",
    "Solo en Dios reposa mi alma",
    "Sed de Dios en el desierto",
    "Súplica contra los conspiradores",
    "A ti, oh Dios, alabanza",
    "Cántico de júbilo · Dios provee",
    "Gracias por las bendiciones",
    "Levántese Dios · marcha del pueblo",
    "Sálvame, oh Dios · sufrimiento mesiánico",
    "Apresúrate, Señor, a librarme",
    "En ti me he refugiado",
    "El rey justo y eterno",
    "¿Por qué prosperan los impíos?",
    "Recordando las gestas de Dios",
    "Lecciones de la historia",
    "Asaf: «Cuán bueno es Dios para Israel»",
    "Dios es Juez",
    "Cuando elija el tiempo",
    "Lamento por Jerusalén",
    "Recordando las maravillas",
    "Oración por la restauración",
    "El pastor de Israel",
    "Cántico al Dios poderoso",
    "Dios contra los dioses falsos",
    "Oración contra los enemigos del pueblo",
    "Anhelo del santuario",
    "Avivamiento · restauración",
    "Oración de David afligido",
    "Bondades del Señor",
    "Maskil sobre la disciplina",
    "Refugio bajo las alas del Altísimo",
    "Bueno es alabar al Señor",
    "El Señor reina · vestido de hermosura",
    "Dios juez de la tierra",
    "Venid, aclamemos al Señor",
    "Cantad al Señor cántico nuevo",
    "Júbilo por el reinado del Señor",
    "El Señor reina · trémble la tierra",
    "Cantad al Señor un cántico nuevo",
    "Servid al Señor con alegría",
    "El compromiso del rey justo",
    "El afligido derrama su queja",
    "Bendice, alma mía, al Señor",
    "Bendice al Señor · maravillas de la creación",
    "Recordando los actos del Señor",
    "Bondades en el desierto y exilio",
    "Cántico mesiánico",
    "El Señor a mi Señor",
    "Aleluya · alabanza por el favor",
    "Bienaventurado el que teme al Señor",
    "Aleluya · siervos del Señor",
    "Cuando Israel salió de Egipto",
    "No a nosotros, Señor",
    "Cántico tras la liberación",
    "Alabad al Señor, naciones todas (el más corto)",
    "Aleluya · misericordias del Señor",
    "Bienaventurados los íntegros · la Ley",
    "Súplica en la angustia",
    "Mi ayuda viene del Señor",
    "Yo me alegré con los que me decían: ‘a la casa del Señor’",
    "Levanto mis ojos hacia ti",
    "A no haber sido por el Señor",
    "Los que confían en el Señor son como el monte Sión",
    "Cuando el Señor hizo volver la cautividad",
    "Si el Señor no edificare la casa",
    "Bienaventurado el que teme al Señor",
    "Súplica contra los enemigos",
    "Desde lo profundo",
    "Como un niño destetado",
    "Donde habitan los hermanos en armonía",
    "Bendecid al Señor, siervos del Señor",
    "Recordando las grandezas de Dios",
    "Junto a los ríos de Babilonia",
    "Te alabaré con todo mi corazón",
    "Señor, tú me has examinado",
    "Líbrame, Señor, del hombre malo",
    "Señor, a ti clamo",
    "El justo me castigará · misericordia",
    "Voz mía al Señor clamé",
    "Oye mi oración, Señor",
    "Bendito sea el Señor, mi roca",
    "Te exaltaré, mi Dios, mi Rey",
    "Alaba, alma mía, al Señor",
    "Cuán bueno es cantar salmos",
    "Aleluya · alabad desde los cielos",
    "Cantad al Señor un cántico nuevo",
    "Cantad al Señor un cántico nuevo (149)",
    "Toda alabanza al Señor en su santuario",
    "Aleluya · todo lo que respira alabe al Señor",
  ],
  PRO: [
    "El temor del Señor",
    "El valor de la sabiduría",
    "Fíate en el Señor",
    "Sobre todas las cosas, guarda tu corazón",
    "Advertencia contra la inmoralidad",
    "Pereza, malicia y adulterio",
    "Advertencia contra la mujer extraña",
    "El llamado de la Sabiduría",
    "Sabiduría y necedad",
    "Justicia frente a maldad",
    "El justo y el malvado",
    "El amor a la disciplina",
    "El justo aborrece la mentira",
    "El sabio y el necio",
    "La blanda respuesta",
    "Planes del corazón",
    "Más vale paz con poco",
    "Lengua que destruye o sana",
    "Pobre que anda en integridad",
    "El vino y la sabiduría",
    "Buen nombre y riquezas",
    "Trabajo, honra y sabiduría",
    "No tengas envidia del malo",
    "Más proverbios de los sabios",
    "Proverbios copiados por los varones de Ezequías",
    "Disciplina de la familia",
    "El hierro se aguza con hierro",
    "El justo aleja al impío",
    "Justicia, rey y mansedumbre",
    "Palabras de Agur",
    "La mujer virtuosa",
  ],
  ECC: [
    "Vanidad de vanidades",
    "Placer, trabajo y sabiduría · todo vanidad",
    "Tiempo para todo",
    "Opresión, trabajo y soledad",
    "Reverencia y honestidad",
    "La codicia es vana",
    "Mejor el día de la muerte",
    "El sabio y el necio",
    "El mismo destino para todos",
    "La sabiduría supera al poder",
    "Echa tu pan sobre las aguas",
    "Acuérdate de tu Creador",
  ],
  SNG: [
    "El beso del amado",
    "Rosa de Sarón · lirio de los valles",
    "Sueño nupcial",
    "El amado describe a la amada",
    "Búsqueda nocturna",
    "Reencuentro en el jardín",
    "Belleza de la amada",
    "Fuerte como la muerte es el amor",
  ],

  // ─────────── AT · Profetas mayores ───────────
  ISA: [
    "Visión de un pueblo enfermo",
    "El monte de Jehová · días futuros",
    "Juicio sobre Jerusalén",
    "Renuevo del Señor",
    "Cántico de la viña",
    "Visión de la gloria de Dios",
    "Señal de Emanuel",
    "Hijo y maravilloso Consejero anunciado",
    "Un niño nos es nacido",
    "Ay de Asiria",
    "Vara del tronco de Isaí",
    "Cántico de salvación",
    "Carga contra Babilonia",
    "Caída del rey de Babilonia",
    "Carga contra Moab",
    "Más sobre Moab",
    "Carga contra Damasco",
    "Carga contra Etiopía",
    "Carga contra Egipto",
    "Profecía simbólica contra Egipto y Etiopía",
    "Carga del desierto del mar",
    "Carga del valle de la visión",
    "Carga contra Tiro",
    "Devastación de la tierra",
    "Cántico al Señor",
    "Cántico de los redimidos",
    "Liberación de Israel",
    "Ay de Efraín y su corona de soberbia",
    "Ay de Ariel (Jerusalén)",
    "Ay de los que descienden a Egipto",
    "Confianza vana en Egipto",
    "El rey justo viene",
    "Llamado de hombres y mujeres",
    "Ay del destructor",
    "Juicio sobre las naciones",
    "Florecerá el desierto",
    "Senaquerib invade Judá",
    "Oración de Ezequías · derrota asiria",
    "Enfermedad y sanidad de Ezequías",
    "Embajada de Babilonia",
    "Consolad, consolad a mi pueblo",
    "El Siervo escogido",
    "El nuevo éxodo",
    "El primero y el último",
    "Idolatría ridiculizada · Ciro mencionado",
    "Llamado de Ciro · «Yo soy el Señor»",
    "Caída de Babilonia",
    "Más sobre Babilonia",
    "Israel obstinado, llamado a salir",
    "El Siervo del Señor (segundo cántico)",
    "El Siervo obediente (tercer cántico)",
    "Despertad, brazo del Señor",
    "El Siervo Sufriente",
    "Cántico de la estéril",
    "Venid a las aguas",
    "Salvación a los extraños",
    "Idolatría y promesa",
    "El verdadero ayuno",
    "Pecados que separan de Dios",
    "Levántate, resplandece",
    "Año aceptable del Señor",
    "El centinela sobre los muros",
    "Pisador en el lagar",
    "Oración por intervención divina",
    "Respuesta de Dios · juicio y promesa",
    "Nuevos cielos y nueva tierra",
  ],
  JER: [
    "Llamado de Jeremías",
    "Israel olvidó al Señor",
    "Vuelvan los hijos infieles",
    "Anuncio de invasión desde el norte",
    "Pecado e idolatría",
    "Asedio inminente sobre Jerusalén",
    "Sermón en la puerta del Templo",
    "Lamento por los obstinados",
    "Sea el llorar mi consuelo",
    "Idolatría y el Dios verdadero",
    "Conspiración contra el profeta",
    "Si corriste con los de a pie",
    "El cinto de lino podrido",
    "Sequía · oración rechazada",
    "Llamados a sufrir",
    "Soledad del profeta",
    "El pecado de Judá escrito en bronce",
    "El alfarero y el barro",
    "La botija quebrada · Tofet",
    "Acusación contra Pasur · queja del profeta",
    "Profecía contra Sedequías",
    "Contra los reyes de Judá",
    "Pastores infieles · Renuevo justo",
    "Higos buenos e higos malos",
    "Setenta años de cautiverio",
    "Juicio sobre Jeremías",
    "Yugos sobre las naciones",
    "Falso profeta Hananías",
    "Carta a los exiliados",
    "Promesa de restauración",
    "El Nuevo Pacto",
    "La compra del campo en Anatot",
    "Promesa de paz futura",
    "Liberación de los esclavos hebreos",
    "Los recabitas",
    "Quemada la profecía · reescrita",
    "Sedequías y los caldeos",
    "Jeremías en la cisterna",
    "Caída de Jerusalén",
    "Jeremías liberado",
    "Gedalías asesinado",
    "Los remanentes huyen a Egipto",
    "Jeremías es llevado a Egipto",
    "Idolatría de los judíos en Egipto",
    "Promesa a Baruc",
    "Profecía contra Egipto",
    "Profecía contra los filisteos",
    "Profecía contra Moab",
    "Profecías contra Amón, Edom, Damasco, Cedar y Elam",
    "Profecía sobre Babilonia (1)",
    "Profecía sobre Babilonia (2)",
    "Caída de Jerusalén · resumen",
  ],
  LAM: [
    "Jerusalén como viuda",
    "Día de la ira del Señor",
    "Nuevas son cada mañana",
    "Castigo de Sion",
    "Súplica final por la restauración",
  ],
  EZK: [
    "Visión del trono · seres vivientes",
    "Comer el rollo",
    "Atalaya · mudez del profeta",
    "Acto profético: el cerco de Jerusalén",
    "Acto profético: el cabello cortado",
    "Profecía contra los montes de Israel",
    "El fin viene · día de la ira",
    "Visión de la gloria abandonando el Templo",
    "Marca en la frente del fiel",
    "Carbones esparcidos · gloria parte",
    "Castigo a los líderes",
    "Profecía simbólica del exilio",
    "Falsos profetas y profetisas",
    "Ancianos idólatras",
    "La vid inútil",
    "Jerusalén infiel",
    "Parábola de las dos águilas",
    "El alma que peca, esa morirá",
    "Endecha por los príncipes",
    "Historia de la rebeldía de Israel",
    "Espada del Señor · contra Amón",
    "Pecados de Jerusalén",
    "Oholá y Oholibá",
    "La olla hirviente · muerte de la esposa",
    "Profecía contra Amón, Moab, Edom y Filistea",
    "Tiro condenada",
    "Endecha sobre Tiro",
    "Príncipe y rey de Tiro · Sidón",
    "Profecía contra Egipto",
    "Egipto destruida por Babilonia",
    "Faraón comparado con un cedro",
    "Endecha sobre Faraón",
    "Atalaya responsable · arrepentimiento",
    "Pastores infieles · el pastor verdadero",
    "Profecía contra el monte de Seir",
    "Promesa de restauración · corazón nuevo",
    "Valle de los huesos secos · dos varas",
    "Profecía contra Gog (1)",
    "Profecía contra Gog (2)",
    "Visión del nuevo Templo",
    "Mediciones del Templo",
    "Más detalles del Templo",
    "Gloria del Señor vuelve · altar consagrado",
    "Reglas para sacerdotes",
    "El príncipe · ofrendas",
    "Más reglas · cocinas",
    "Río que sale del Templo · fronteras",
    "Tribus y porciones · «el Señor está allí»",
  ],
  DAN: [
    "Daniel y sus tres amigos en la corte",
    "Sueño de la estatua",
    "Los tres en el horno",
    "Sueño del árbol · locura de Nabucodonosor",
    "Festín de Belsasar · escritura en la pared",
    "Daniel en el foso de los leones",
    "Visión de las cuatro bestias · Hijo del Hombre",
    "Visión del carnero y el macho cabrío",
    "Las setenta semanas",
    "Visión del varón vestido de lino",
    "Reyes del norte y del sur",
    "Tiempo del fin · resurrección",
  ],

  // ─────────── AT · Profetas menores ───────────
  HOS: [
    "Oseas, Gomer y los hijos simbólicos",
    "Israel adúltera · llamada a volver",
    "Oseas redime a Gomer",
    "Acusación contra Israel",
    "Juicio sobre Efraín",
    "Vamos y volvamos al Señor",
    "Adulterio de Efraín",
    "Israel siembra viento, siega torbellino",
    "Castigo por la apostasía",
    "Sembrad para vosotros en justicia",
    "Cuando Israel era muchacho",
    "Engaño de Efraín",
    "Muerte y Seol vencidos",
    "Vuelve, Israel · sanidad prometida",
  ],
  JOL: [
    "Plaga de langostas",
    "El día del Señor · derramamiento del Espíritu",
    "Juicio en el valle de Josafat",
  ],
  AMO: [
    "Juicios contra las naciones",
    "Juicio contra Judá e Israel",
    "Acusación contra Samaria",
    "Llamamientos rechazados",
    "Llamado al arrepentimiento",
    "Ay de los que confían en el lujo",
    "Visión de las langostas, el fuego y la plomada",
    "Cesto de fruta madura",
    "Restauración del tabernáculo de David",
  ],
  OBA: ["Juicio sobre Edom y restauración de Sion"],
  JON: [
    "Jonás huye a Tarsis",
    "Oración desde el vientre del pez",
    "Predicación en Nínive · arrepentimiento",
    "Enojo de Jonás · la calabacera",
  ],
  MIC: [
    "Lamento por Samaria y Jerusalén",
    "Ay de los que traman maldad",
    "Líderes corruptos · falsos profetas",
    "El monte del Señor · Belén anunciada",
    "El gobernante que vendrá de Belén",
    "¿Qué pide el Señor? Justicia, misericordia y humildad",
    "Esperanza del remanente",
  ],
  NAM: [
    "El Señor, vengador y misericordioso",
    "Caída de Nínive",
    "Lamento sobre la ciudad sanguinaria",
  ],
  HAB: [
    "Pregunta del profeta · respuesta de Dios",
    "El justo por su fe vivirá",
    "Oración cántico · gozo en el Señor",
  ],
  ZEP: [
    "El gran día del Señor",
    "Llamado al arrepentimiento · juicio universal",
    "Promesa de restauración",
  ],
  HAG: [
    "Llamado a edificar el Templo",
    "Gloria mayor del segundo Templo · Zorobabel anillo",
  ],
  ZEC: [
    "Visión del hombre en el caballo bermejo",
    "Visión del cuerno y los herreros",
    "Sumo sacerdote acusado",
    "Candelero y dos olivos",
    "Rollo volador · mujer en la efa",
    "Cuatro carros · coronación de Josué",
    "Llamado al ayuno verdadero",
    "Promesas a Jerusalén",
    "Rey humilde sobre pollino",
    "Reunión del rebaño",
    "Los dos cayados · treinta piezas",
    "El traspasado · luto en Jerusalén",
    "Fuente para la limpieza · pastor herido",
    "Día del Señor sobre el monte de los Olivos",
  ],
  MAL: [
    "El amor de Dios por Israel · ofrendas defectuosas",
    "Sacerdotes corruptos · matrimonios mixtos",
    "El mensajero del pacto · diezmos",
    "El Sol de Justicia · Elías por venir",
  ],

  // ─────────── NT · Evangelios ───────────
  MAT: [
    "Genealogía de Jesús · nacimiento",
    "Los magos · huida a Egipto",
    "Juan el Bautista · bautismo de Jesús",
    "Tentación · primeros discípulos",
    "Sermón del Monte (1) · Bienaventuranzas",
    "Sermón del Monte (2) · Padre nuestro",
    "Sermón del Monte (3) · juzgar y la casa sobre la roca",
    "Milagros · centurión, suegra de Pedro",
    "Llamamiento de Mateo · paralítico",
    "Envío de los doce",
    "Juan en la cárcel · «venid a mí»",
    "Espigas y endemoniado · pecado contra el Espíritu",
    "Parábolas del Reino",
    "Muerte de Juan · multiplicación de panes · sobre el agua",
    "Tradición humana · multitud y siete panes",
    "Confesión de Pedro · anuncio de la cruz",
    "Transfiguración · sanación del epiléptico",
    "El mayor en el Reino · el siervo no perdonador",
    "Divorcio · niños · joven rico",
    "Obreros de la viña · tercer anuncio · ciegos en Jericó",
    "Entrada triunfal · purificación del Templo",
    "Bodas del hijo del rey · tributo al César",
    "Ay sobre los fariseos",
    "Discurso del monte de los Olivos (1)",
    "Discurso del monte de los Olivos (2) · juicio final",
    "Última cena · arresto",
    "Crucifixión y muerte",
    "Resurrección · Gran Comisión",
  ],
  MRK: [
    "Juan el Bautista · bautismo y tentación · primeros milagros",
    "Paralítico · llamado de Leví · disputas",
    "Mano seca · designación de los doce · familia espiritual",
    "Parábolas · tormenta calmada",
    "Endemoniado gadareno · hija de Jairo · mujer con flujo",
    "Rechazo en Nazaret · envío de los doce · muerte de Juan",
    "Tradición humana · sirofenicia · sordomudo",
    "Cuatro mil saciados · ciego de Betsaida · confesión de Pedro",
    "Transfiguración · epiléptico · el mayor en el Reino",
    "Divorcio · niños · joven rico · Bartimeo",
    "Entrada triunfal · higuera maldecida · autoridad",
    "Viñadores malvados · tributo · gran mandamiento",
    "Profecía del fin",
    "Unción en Betania · última cena · Getsemaní",
    "Juicio · crucifixión · muerte",
    "Resurrección · apariciones · final",
  ],
  LUK: [
    "Prólogo · anunciaciones · Magníficat · nacimiento de Juan",
    "Nacimiento de Jesús · pastores · presentación",
    "Juan el Bautista · genealogía de Jesús",
    "Tentación · Nazaret · primeros milagros en Cafarnaúm",
    "Pesca milagrosa · leproso · llamado de Leví",
    "Sermón del llano · «amen a sus enemigos»",
    "Centurión · hijo de la viuda · pecadora perdonada",
    "Parábola del sembrador · gadareno · Jairo",
    "Envío de los doce · multiplicación · transfiguración",
    "Envío de los setenta · buen samaritano · Marta y María",
    "Padre nuestro · pedid y se os dará · señal de Jonás",
    "Hipocresía · ricos · velando",
    "Arrepentíos · higuera estéril · paralítica curada",
    "Cenando con el fariseo · gran cena · costo del discipulado",
    "Oveja, dracma, hijo pródigo",
    "Mayordomo astuto · rico y Lázaro",
    "Diez leprosos · venida del Hijo del Hombre",
    "Viuda persistente · fariseo y publicano · joven rico",
    "Zaqueo · minas · entrada triunfal · Templo",
    "Autoridad · viñadores · resurrección · ofrenda de la viuda",
    "Profecía sobre Jerusalén y el fin",
    "Última cena · oración en Getsemaní · arresto",
    "Juicios · crucifixión · muerte",
    "Resurrección · Emaús · ascensión",
  ],
  JHN: [
    "El Verbo · primeros discípulos",
    "Bodas de Caná · purificación del Templo",
    "Nicodemo · «de tal manera amó Dios»",
    "Samaritana · sanidad a distancia",
    "Paralítico de Betesda · testimonio del Padre",
    "Cinco mil saciados · pan de vida",
    "Conflicto en la fiesta de los Tabernáculos",
    "Mujer adúltera · «Yo soy la luz del mundo»",
    "Ciego de nacimiento",
    "El buen pastor",
    "Resurrección de Lázaro",
    "Unción en Betania · entrada triunfal",
    "Lavamiento de los pies · anuncio de Judas",
    "«Yo soy el camino, la verdad y la vida»",
    "La vid verdadera",
    "Promesa del Consolador",
    "Oración sacerdotal",
    "Arresto · negación de Pedro",
    "Crucifixión y muerte",
    "Resurrección · «Tomás incrédulo»",
    "Aparición en el mar · «¿me amas?»",
  ],
  ACT: [
    "Ascensión · elección de Matías",
    "Pentecostés · primera predicación",
    "Sanación del cojo · sermón en el pórtico",
    "Pedro y Juan ante el sanedrín · oración en común",
    "Ananías y Safira · más sanidades",
    "Elección de los siete · arresto de Esteban",
    "Discurso de Esteban · martirio",
    "Felipe en Samaria · eunuco etíope",
    "Conversión de Saulo",
    "Cornelio · visión de Pedro",
    "Pedro explica en Jerusalén · iglesia en Antioquía",
    "Martirio de Jacobo · liberación de Pedro",
    "Primer viaje misionero (1)",
    "Primer viaje misionero (2) · Listra y Derbe",
    "Concilio de Jerusalén",
    "Segundo viaje · Lidia · cárcel en Filipos",
    "Tesalónica, Berea, Atenas",
    "Corinto · Aquila y Priscila",
    "Tercer viaje · Éfeso · disturbio de Demetrio",
    "Macedonia · resurrección de Eutico · despedida en Mileto",
    "Camino a Jerusalén · arresto",
    "Discurso de Pablo · ciudadano romano",
    "Conspiración · enviado a Cesarea",
    "Pablo ante Félix",
    "Pablo ante Festo · apelación al César",
    "Pablo ante Agripa",
    "Naufragio en el viaje a Roma",
    "Malta · llegada a Roma",
  ],

  // ─────────── NT · Cartas Paulinas ───────────
  ROM: [
    "Saludo · poder del evangelio · ira contra la impiedad",
    "Juicio sobre judíos y gentiles",
    "Todos pecaron · justicia por la fe",
    "Abraham, ejemplo de fe",
    "Justificación · Adán y Cristo",
    "Muertos al pecado, vivos en Cristo",
    "Conflicto interior",
    "Vida en el Espíritu · «nada nos separa»",
    "Soberanía de Dios e Israel",
    "Salvación al alcance · oración por Israel",
    "Restauración futura de Israel",
    "Sacrificio vivo · dones · amor sin fingimiento",
    "Sujeción a las autoridades · amor",
    "Débil y fuerte en la fe",
    "Vivir para servir a los demás",
    "Saludos finales",
  ],
  "1CO": [
    "Divisiones · sabiduría de Dios",
    "Sabiduría humana vs. espiritual",
    "Ministros de Cristo · un solo cimiento",
    "Mayordomos de los misterios",
    "Inmoralidad en la iglesia",
    "Pleitos entre hermanos · «glorificad a Dios»",
    "Matrimonio · vírgenes",
    "Comida sacrificada a ídolos",
    "Derechos del apóstol · «corred de tal manera»",
    "Tipología del éxodo · tentación",
    "Mujeres orando · cena del Señor",
    "Dones espirituales · un solo cuerpo",
    "El amor",
    "Lenguas y profecía",
    "La resurrección",
    "Ofrenda para los santos · saludos finales",
  ],
  "2CO": [
    "Saludo · sufrimientos compartidos",
    "Perdón al ofensor · ministro del Nuevo Pacto",
    "Velo del antiguo pacto · libertad",
    "Tesoro en vasos de barro",
    "Tabernáculo eterno · ministerio de la reconciliación",
    "Vivir como ministros · no os unáis con incrédulos",
    "Gozo por el arrepentimiento de los corintios",
    "Ofrenda generosa (1)",
    "Ofrenda generosa (2)",
    "Defensa apostólica",
    "Pablo y los falsos apóstoles",
    "Visión del paraíso · aguijón en la carne",
    "Última visita · examen propio",
  ],
  GAL: [
    "Saludo · «otro evangelio»",
    "Concilio en Jerusalén · Pablo confronta a Pedro",
    "El justo vivirá por la fe · la ley como ayo",
    "Hijos por adopción · Sara y Agar",
    "Libertad en Cristo · fruto del Espíritu",
    "Restaurar al caído · cargar la cruz de Cristo",
  ],
  EPH: [
    "Bendiciones espirituales en Cristo",
    "Salvos por gracia · un solo pueblo",
    "Misterio revelado · oración de Pablo",
    "Un solo Señor, una sola fe",
    "Andad en amor · esposos y esposas",
    "Padres e hijos · armadura de Dios",
  ],
  PHP: [
    "Saludo · «vivir es Cristo»",
    "Humillación de Cristo · ejemplo a seguir",
    "Cuidado de los falsos · prosigo al blanco",
    "Gozaos siempre · «todo lo puedo»",
  ],
  COL: [
    "Saludo · supremacía de Cristo",
    "Plenitud en Cristo · libres de filosofías",
    "Buscad las cosas de arriba · nueva vida",
    "Sabiduría con los de afuera · saludos",
  ],
  "1TH": [
    "Ejemplo de los tesalonicenses",
    "Ministerio de Pablo entre ellos",
    "Envío de Timoteo · oración",
    "Voluntad de Dios · venida del Señor",
    "Velad · «orad sin cesar»",
  ],
  "2TH": [
    "Saludo · juicio venidero",
    "El hombre de pecado",
    "Quien no quiere trabajar, tampoco coma",
  ],
  "1TI": [
    "Saludo · falsos maestros",
    "Oración por todos · enseñanza para las mujeres",
    "Requisitos de obispos y diáconos",
    "Falsos maestros · sé ejemplo",
    "Trato con viudas y ancianos",
    "Esclavos · «raíz de todos los males»",
  ],
  "2TI": [
    "Aviva el fuego del don de Dios",
    "Soldado, atleta, labrador",
    "Tiempos peligrosos · la Escritura inspirada",
    "Predica la palabra · «he peleado la buena batalla»",
  ],
  TIT: [
    "Ancianos en Creta",
    "Enseñanzas para diferentes grupos",
    "Sujeción a las autoridades · salvación por gracia",
  ],
  PHM: ["Apelación a Filemón por Onésimo"],

  // ─────────── NT · Hebreos + Generales ───────────
  HEB: [
    "Cristo, superior a los profetas y ángeles",
    "Cristo, hecho hermano de los hombres",
    "Cristo, superior a Moisés",
    "Sumo Sacerdote misericordioso",
    "Sacerdocio según el orden de Melquisedec",
    "Madurez en la fe · ancla del alma",
    "Melquisedec y el sacerdocio eterno",
    "Mediador del Nuevo Pacto",
    "Templo terrenal y celestial",
    "Un solo sacrificio · perseverancia",
    "Héroes de la fe",
    "Mirando a Jesús · disciplina del Padre",
    "Amor fraternal · «Jesucristo el mismo»",
  ],
  JAS: [
    "Pruebas y tentaciones · oíd y haced",
    "Fe y obras",
    "Domando la lengua",
    "Sujetaos a Dios · planes humildes",
    "Oración del justo · paciencia",
  ],
  "1PE": [
    "Esperanza viva · sed santos",
    "Piedra viva · linaje escogido",
    "Esposos, esposas y sufrimiento",
    "Vivir conforme a Dios",
    "Pastores y rebaño · «echen toda su ansiedad»",
  ],
  "2PE": [
    "Llamamiento y elección · profecía",
    "Falsos maestros",
    "El día del Señor · esperanza de nuevos cielos",
  ],
  "1JN": [
    "Comunión con la luz",
    "Mandamiento del amor · «no améis al mundo»",
    "Hijos de Dios · «amémonos los unos a los otros»",
    "Espíritu de verdad · Dios es amor",
    "Fe que vence al mundo · vida eterna",
  ],
  "2JN": ["Andad en verdad y amor · cuídate de los engañadores"],
  "3JN": ["Elogio a Gayo · Diótrefes y Demetrio"],
  JUD: ["Contended por la fe · doxología final"],
  REV: [
    "Visión del Hijo del Hombre",
    "Cartas a Éfeso, Esmirna, Pérgamo, Tiatira",
    "Cartas a Sardis, Filadelfia, Laodicea",
    "Trono del cielo",
    "El rollo y el Cordero",
    "Apertura de seis sellos",
    "Los 144.000 · multitud incontable",
    "Séptimo sello · cuatro trompetas",
    "Quinta y sexta trompetas",
    "El ángel y el librito",
    "Dos testigos · séptima trompeta",
    "La mujer, el dragón y el niño",
    "Las dos bestias",
    "El Cordero y los 144.000 · cosecha",
    "Cántico de Moisés y del Cordero",
    "Las siete copas",
    "Babilonia, la gran ramera",
    "Caída de Babilonia",
    "Aleluya · bodas del Cordero · jinete fiel",
    "Mil años · juicio final",
    "Nueva Jerusalén",
    "Río de vida · «Ven, Señor Jesús»",
  ],
};

/** Devuelve el subtítulo curado para un capítulo, o null si no existe. */
export function tituloCapitulo(
  libroCodigo: string,
  capitulo: number
): string | null {
  const arr = TITULOS_CAPITULOS[libroCodigo];
  if (!arr) return null;
  if (capitulo < 1 || capitulo > arr.length) return null;
  return arr[capitulo - 1] || null;
}
